### ISSUE TITLE
dotnet mono crash

### ISSUE THREAD

**Issue by khwiri** [TheAngryByrd/dotnet-mono#46]
I'm getting the following error when running `dotnet mono -f net461`.

```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Threading, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Logary.Facade.Global.Flyweight.withLogger[a](FSharpFunc`2 action)
   at Logary.Facade.LoggerEx.logWithTimeout@219.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@839.Invoke(AsyncParams`1 args)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](AsyncImplResult`1 res)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronouslyInCurrentThread[a](CancellationToken token, FSharpAsync`1 computation)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at Logary.Facade.LoggerEx.Logger.logSync(Logger x, Message message)
   at DotnetMono.Main.main'@200.Invoke(Unit unitVar)
   at Chessie.ErrorHandling.Trial.fSuccess@66-12[j,l,k](FSharpFunc`2 b, j x, FSharpList`1 msgs)
   at DotnetMono.Main.main(String[] argv)
```

**Comment by TheAngryByrd** [comment]
Could you try updating to `0.5.7-beta002`?
